# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create({name: "Jonathan H", username: "hejeong", password: "hejeong", email: "jon@jon.com"})
User.create({name: "Austin K", username: "austin", password: "austin", email: "austin@austin.com"})
User.create({name: "Salman O", username: "salman", password: "salman", email: "salman@salman.com"})

Post.create({title: "Running the Half Marathon", description: "The half marathon may immediately seem very daunting. But even you can run it! Learn how to prepare for your first Half Marathon", user_id: 1, content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sem viverra aliquet eget sit amet. Donec ultrices tincidunt arcu non. Ac tincidunt vitae semper quis lectus nulla. Id porta nibh venenatis cras sed felis eget velit aliquet. Nibh mauris cursus mattis molestie a iaculis at. Diam phasellus vestibulum lorem sed. Pellentesque elit eget gravida cum sociis. Porttitor eget dolor morbi non arcu risus quis varius. Eu augue ut lectus arcu bibendum at. Aliquet bibendum enim facilisis gravida neque convallis a. Pretium quam vulputate dignissim suspendisse in est ante in. Ullamcorper a lacus vestibulum sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Id volutpat lacus laoreet non curabitur. Ipsum faucibus vitae aliquet nec ullamcorper. Nunc sed id semper risus. Fames ac turpis egestas integer eget aliquet nibh praesent. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Tortor pretium viverra suspendisse potenti nullam ac tortor.\nMassa tincidunt dui ut ornare. Sit amet luctus venenatis lectus magna fringilla urna porttitor. Nisi est sit amet facilisis magna. Id volutpat lacus laoreet non curabitur gravida. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Nam libero justo laoreet sit amet. Arcu risus quis varius quam quisque id diam vel quam. Facilisis gravida neque convallis a cras. Turpis egestas pretium aenean pharetra magna. Mauris pharetra et ultrices neque ornare aenean. Turpis egestas maecenas pharetra convallis posuere. Eu turpis egestas pretium aenean. In est ante in nibh mauris cursus. Auctor urna nunc id cursus metus.", image_url: "http://enlightetech.com/wp-content/uploads/2019/02/Landscapes-1.jpg"});
Post.create({title: "Facing Your Injuries From Your Runs", description: "I experience many injuries myself. It's very important to keep yourself in good condition, but when you can't, you have to learn how to prevent further damage. Click more to learn how from professional advice!", user_id: 3, content: "OUCH!", image_url: "https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/video/wibbitz/wbz-runners-knee.jpg"});
Post.create({title: "Finding the Right Shoes", description: "Find the right pair of shoes to prevent injuries and run at the peak of your potential.", user_id: 2, content: "\tLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed libero enim sed faucibus turpis in. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Sagittis purus sit amet volutpat consequat mauris. Orci dapibus ultrices in iaculis nunc sed. Risus feugiat in ante metus. Urna molestie at elementum eu facilisis sed odio. Quis eleifend quam adipiscing vitae proin. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Curabitur gravida arcu ac tortor dignissim convallis. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Pulvinar sapien et ligula ullamcorper.\n\tTortor consequat id porta nibh venenatis cras sed. Vitae turpis massa sed elementum tempus egestas sed sed. Egestas congue quisque egestas diam in arcu
    cursus euismod quis. A arcu cursus vitae congue mauris. Cursus eget nunc scelerisque viverra. Lorem donec massa sapien faucibus et. Sodales neque sodales ut etiam. Facilisis leo vel fringilla est ullamcorper. Ornare massa eget egestas purus viverra. Luctus accumsan tortor posuere ac ut consequat semper. Commodo elit at imperdiet dui accumsan. Ultricies mi eget mauris pharetra et ultrices. A cras semper auctor neque vitae tempus quam. Accumsan in nisl nisi scelerisque eu ultrices vitae.\n\tAliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Luctus venenatis lectus magna fringilla. Quam adipiscing vitae proin sagittis. Lorem sed risus ultricies tristique nulla aliquet enim. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Nisi vitae suscipit tellus mauris a diam maecenas sed. Et malesuada fames ac turpis egestas sed tempus. Nunc pulvinar sapien et ligula. Gravida arcu ac tortor dignissim convallis aenean et. Duis convallis convallis tellus id interdum. Purus faucibus ornare suspendisse sed. Blandit volutpat maecenas volutpat blandit aliquam etiam erat. Porttitor leo a diam sollicitudin. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Hendrerit dolor magna eget est lorem ipsum. Viverra maecenas accumsan lacus vel facilisis volutpat est.\n\tSit amet est placerat in egestas erat imperdiet sed. Vulputate ut pharetra sit amet aliquam id. Feugiat sed lectus vestibulum mattis ullamcorper. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Quam nulla porttitor massa id neque aliquam. Eget dolor morbi non arcu risus quis varius quam. Mi proin sed libero enim sed. Volutpat lacus laoreet non curabitur gravida arcu ac. Maecenas sed enim ut sem viverra aliquet. Ac tincidunt vitae semper quis lectus nulla at. Viverra tellus in hac habitasse platea dictumst. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Dignissim suspendisse in est ante in nibh. Tristique senectus et netus et malesuada fames ac turpis egestas. Ut sem nulla pharetra diam.\n\tMagnis dis parturient montes nascetur ridiculus. Vel quam elementum pulvinar etiam non quam lacus. Risus in hendrerit gravida rutrum quisque non tellus orci ac. Blandit massa enim nec dui nunc mattis enim ut. Nam at lectus urna duis convallis. Mi sit amet mauris commodo. Condimentum vitae sapien pellentesque habitant. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Amet risus nullam eget felis eget nunc lobortis mattis. Sed odio morbi quis commodo odio aenean sed adipiscing. Lorem sed risus ultricies tristique nulla aliquet. Laoreet suspendisse interdum consectetur libero id. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus.", image_url: "https://images.unsplash.com/photo-1469395446868-fb6a048d5ca3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80"});
